## **UJI HIPOTHESIS 3:**

#### 3. BMI laki-laki dan perempuan sama
  
      hipotesis yang akan kita uji adalah:
                              
$$H_0: \mu_{BMImale} = \mu_{BMIfemale}$$
$$H_1: \mu_{BMImale} \not= \mu_{BMIfemale}$$

In [143]:
# load data
import pandas as pd
import numpy as np

# visualization
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

from scipy.stats import t
from scipy.stats import ttest_ind

data = pd.read_csv('insurance.csv')
#sampling 100 data
data = data.sample(100)

In [144]:
#data BMI laki-laki
sample_BMImale = data.loc[data.sex == "male"]
sample_BMImale

      age   sex     bmi  children smoker     region      charges
747    19  male  21.755         0     no  northwest   1627.28245
683    53  male  24.320         0     no  northwest   9863.47180
93     35  male  34.770         2     no  northwest   5729.00530
1233   58  male  23.300         0     no  southwest  11345.51900
2      28  male  33.000         3     no  southeast   4449.46200
1108   26  male  30.000         1     no  southwest   2904.08800
965    35  male  27.100         1     no  southwest   4746.34400
331    52  male  27.360         0    yes  northwest  24393.62240
224    42  male  24.640         0    yes  southeast  19515.54160
506    22  male  31.350         1     no  northwest   2643.26850
988    34  male  34.675         0     no  northeast   4518.82625
263    19  male  36.955         0    yes  northwest  36219.40545
310    50  male  26.600         0     no  southwest   8444.47400
1274   26  male  27.060         0    yes  southeast  17043.34140
582    39  male  45.430         2     no  southeast   6356.27070
936    44  male  29.735         2     no  northeast  32108.66282
598    43  male  32.600         2     no  southwest   7441.50100
698    56  male  33.725         0     no  northwest  10976.24575
223    19  male  34.800         0    yes  southwest  34779.61500
1081   32  male  27.835         1     no  northwest   4454.40265
97     55  male  38.280         0     no  southeast  10226.28420
982    31  male  25.900         3    yes  southwest  19199.94400
1186   20  male  35.625         3    yes  northwest  37465.34375
136    19  male  34.100         0     no  southwest   1261.44200
452    24  male  23.400         0     no  southwest   1969.61400
1265   64  male  23.760         0    yes  southeast  26926.51440
15     19  male  24.600         1     no  southwest   1837.23700
940    18  male  23.210         0     no  southeast   1121.87390
776    40  male  32.300         2     no  northwest   6986.69700
917    45  male  22.895         0    yes  northeast  35069.37452
741    27  male  29.150         0    yes  southeast  18246.49550
217    27  male  23.100         0     no  southeast   2483.73600
740    45  male  24.035         2     no  northeast   8604.48365
165    47  male  28.215         4     no  northeast  10407.08585
155    44  male  39.520         0     no  northwest   6948.70080
993    38  male  28.270         1     no  southeast   5484.46730
1295   20  male  22.000         1     no  southwest   1964.78000
799    33  male  24.795         0    yes  northeast  17904.52705
820    45  male  33.700         1     no  southwest   7445.91800
1245   28  male  24.300         5     no  southwest   5615.36900
171    49  male  30.300         0     no  southwest   8116.68000
689    27  male  31.130         1    yes  southeast  34806.46770
1222   50  male  25.300         0     no  southeast   8442.66700
1217   29  male  37.290         2     no  southeast   4058.11610
374    20  male  33.330         0     no  southeast   1391.52870
645    48  male  30.780         3     no  northeast  10141.13620
325    40  male  34.105         1     no  northeast   6600.20595
841    59  male  24.700         0     no  northeast  12323.93600
914    33  male  24.605         2     no  northwest   5257.50795
105    20  male  28.025         1    yes  northwest  17560.37975
495    20  male  27.930         0     no  northeast   1967.02270
1102   29  male  38.940         1     no  southeast   3471.40960

In [145]:
#data BMI perempuan
sample_BMIfemale = data.loc[data.sex == "female"]
sample_BMIfemale

      age     sex     bmi  children smoker     region      charges
299    48  female  28.880         1     no  northwest   9249.49520
496    31  female  23.600         2     no  southwest   4931.64700
328    64  female  33.800         1    yes  southwest  47928.03000
1330   57  female  25.740         2     no  southeast  12629.16560
1311   33  female  26.695         0     no  northwest   4571.41305
415    43  female  35.640         1     no  southeast   7345.72660
5      31  female  25.740         0     no  southeast   3756.62160
587    34  female  30.210         1    yes  northwest  43943.87610
772    44  female  36.480         0     no  northeast  12797.20962
907    44  female  32.340         1     no  southeast   7633.72060
1169   37  female  34.105         1     no  northwest   6112.35295
1188   43  female  25.270         1    yes  northeast  21771.34230
536    33  female  38.900         3     no  southwest   5972.37800
525    18  female  33.880         0     no  southeast  11482.63485
1276   22  female  30.400         0     no  northeast   2741.94800
760    22  female  34.580         2     no  northeast   3925.75820
703    34  female  26.410         1     no  northwest   5385.33790
66     61  female  39.100         2     no  southwest  14235.07200
921    62  female  33.200         0     no  southwest  13462.52000
168    19  female  31.825         1     no  northwest   2719.27975
1287   36  female  25.900         1     no  southwest   5472.44900
426    38  female  27.265         1     no  northeast   6555.07035
135    22  female  28.050         0     no  southeast   2155.68150
551    32  female  28.930         0     no  southeast   3972.92470
1030   46  female  23.655         1    yes  northwest  21677.28345
548    25  female  28.595         0     no  northeast   3213.62205
21     30  female  32.400         1     no  southwest   4149.73600
543    54  female  47.410         0    yes  southeast  63770.42801
56     58  female  31.825         2     no  northeast  13607.36875
1064   29  female  25.600         4     no  southwest   5708.86700
1010   48  female  22.800         0     no  southwest   8269.04400
188    41  female  32.200         1     no  southwest   6775.96100
1130   39  female  23.870         5     no  southeast   8582.30230
306    28  female  27.500         2     no  southwest  20177.67113
789    62  female  29.920         0     no  southeast  13457.96080
191    36  female  26.200         0     no  southwest   4883.86600
845    60  female  32.450         0    yes  southeast  45008.95550
267    59  female  32.395         3     no  northeast  14590.63205
72     53  female  28.100         3     no  southwest  11741.72600
983    27  female  30.590         1     no  northeast  16796.41194
230    42  female  36.195         1     no  northwest   7443.64305
600    18  female  39.160         0     no  southeast   1633.04440
913    44  female  27.500         1     no  southwest   7626.99300
538    46  female  28.050         1     no  southeast   8233.09750
1163   18  female  28.215         0     no  northeast   2200.83085
483    51  female  39.500         1     no  southwest   9880.06800
117    29  female  27.940         1    yes  southeast  19107.77960
572    30  female  43.120         2     no  southeast   4753.63680

In [146]:
#Menghitung varian sample
np.var(sample_BMImale.bmi), np.var(sample_BMIfemale.bmi)

(28.906938979289933, 28.04036662326388)

In [147]:
#perhitungan uji statistik t untuk uji rata rata 2 sampel menggunakan scipy.stats
stat, p = ttest_ind(a = sample_BMImale.bmi, b = sample_BMIfemale.bmi, equal_var=False, alternative='two-sided')

# Interpretasi Hasil
print('Statistics = %.4f, p = %.4f' % (stat, p))

Statistics = -1.2666, p = 0.2083

In [148]:
alpha = 0.05
# Pengambilan Keputusan
if p > alpha:
    print('Gagal tolak H0') 
else:
    print('Tolak H0')

Gagal tolak H0

Dari pengujian hipotesis diatas, kita mengambil kesimpulan bahwa BMI laki-laki sama dengan perempuan